growthConditions:
  sunlightRequirements:
    - 10  # lvl 1 growth requirement
    - 15  # lvl 2 growth requirement
    - 20  # lvl 3 growth requirement
  waterRequirements:
    - 10  # lvl 1 water requirement
    - 20  # lvl 2 water requirement
    - 30  # lvl 3 water requirement

plants:
  - name: "Carrot"
    growthStages:
      - growth_lvl: 1
        image: "plant1_1"
      - growth_lvl: 2
        image: "plant1_2"
      - growth_lvl: 3
        image: "plant1_3"

  - name: "Corn"
    growthStages:
      - growth_lvl: 1
        image: "plant2_1"
      - growth_lvl: 2
        image: "plant2_2"
      - growth_lvl: 3
        image: "plant2_3"

  - name: "Tomato"
    growthStages:
      - growth_lvl: 1
        image: "plant3_1"
      - growth_lvl: 2
        image: "plant3_2"
      - growth_lvl: 3
        image: "plant3_3"
